### ISSUE TITLE
sample data download links seem dead

### ISSUE THREAD

**Issue by kijoshua** [aligners/funcnorm#3]
When I click the download button, I'm just redirected to http://pni.princeton.edu/ .  No visible errors.

**Comment by bdsinger** [comment]
this is fixed now, it is https://webapps.pni.princeton.edu/funcnorm/download_data.php?action=getinfo  

however we should probably just host the blob here on github , it is 568MB in size so isn't unreasonable by today's standards. The entire 10GB 10-subject dataset is available as of yesterday in nifti format to the PNI internally, but I'm still looking into how that can be made available.
